### PR TITLE
fix: Composer issue with yeoman-environment

### PR DESCRIPTION
**Pull request by erquirogasw**
## Description
This PR fixes the issue related to the [yeoman-environment](https://www.npmjs.com/package/yeoman-environment) version when trying to create a bot from a local template.
Since all the generators use [yeoman-generator](https://www.npmjs.com/package/yeoman-generator) v5.7.0 and this one uses yeoman-environment v3.2.0, we updated yeoman-environment to version 3.2.0 in Composer.

Related to:
fix: [# 1440, # 1432] Component Governance security vulnerability for ejs 2.7.4, 3.1.6 and glob-parent 3.1.0
(https: //github.com/microsoft/botframework-components/pull/ 1461)

## Task Item
#minor

## Screenshots
This screenshot shows a bot created from the [generator-bot-empty](https://github.com/microsoft/botframework-components/tree/main/generators/generator-bot-empty) working.
image

### CODE REVIEW

**Review by ceciliaavila — APPROVED** [review]
All the changes in the yarn.lock file are necessary, right?

**Comment by sw-joelmut** [comment]
We could add a reference to the PR in components, so if someone sees these changes, know they are related.

**Comment by erquirogasw** [comment]
> All the changes in the yarn.lock file are necessary, right?

I ran _yarn_ and _yarn build_ in /Composer locally and the _yarn-berry.lock_ was updated as in the pipeline. I can try leaving only changes related to yeoman.

**Comment by ceciliaavila** [comment]
> > All the changes in the yarn.lock file are necessary, right?
> 
> I ran _yarn_ and _yarn build_ in /Composer locally and the _yarn-berry.lock_ was updated as in the pipeline. I can try leaving only changes related to yeoman.

No, it's ok, I just checked and it looks good. Thanks!

**Comment by erquirogasw** [comment]
> We could add a reference to the PR in components, so if someone sees these changes, know they are related.

Solved. Thanks!

**Review by JhontSouth — APPROVED** [review]

**Pull request closed without merging**
